# Generated by Django 5.0 on 2024-05-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0003_remove_property_user_client_property_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
    ]
