# Generated by Django 5.0 on 2024-05-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0004_alter_property_options_remove_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='street_01',
            new_name='street1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='street_02',
            new_name='street2',
        ),
    ]
