# Generated by Django 5.0 on 2024-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0005_rename_street_01_property_street1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Waterloo', max_length=20),
        ),
    ]
