# Generated by Django 5.0 on 2024-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0006_property_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='prop_type',
        ),
        migrations.AddField(
            model_name='property',
            name='apartment',
            field=models.CharField(default='Apartment', max_length=20),
        ),
    ]
