# Generated by Django 5.0 on 2024-05-29 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0008_remove_property_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='term',
        ),
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
