# Generated by Django 5.0 on 2024-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0009_remove_property_term_property_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='EMPTY'),
        ),
    ]
