# Generated by Django 5.0 on 2024-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0010_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
