# Generated by Django 5.0 on 2024-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0013_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
    ]
