# Generated by Django 5.0.6 on 2024-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0014_property_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(default=False, max_length=3),
            preserve_default=False,
        ),
    ]
