# Generated by Django 5.0.6 on 2024-06-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0015_property_bathrooms_property_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_01',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_02',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_03',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_04',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_05',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
