# Generated by Django 5.0.6 on 2024-06-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hestia', '0017_cart_delete_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
